<?php $monitoring = Mage::helper('monitoring');?>
<?php if($monitoring->active() && $monitoring->getAuthorizationToken()):?>
    <iframe id="frame" width="100%" frameborder="0" src="<?php echo $monitoring->getIframeUrl('settings');?>"></iframe>
    <script type="text/javascript">
        function resizeIframe() {
            var height = document.documentElement.clientHeight;
            height -= document.getElementById('frame').offsetTop;

            // not sure how to get this dynamically
            height -= 20; /* whatever you set your body bottom margin/padding to be */

            document.getElementById('frame').style.height = height +"px";

        };
        document.getElementById('frame').onload = resizeIframe;
        window.onresize = resizeIframe;
    </script>
<?php endif;?>
